### ISSUE TITLE
Missing dependencies on Auto Map Markers?

### ISSUE THREAD

**Issue by sirzento** [egocarib/Vintage-Story-Mods#12]
I am trying to get this mod running on VS version 1.18.10 but I can't activate the mod because of missing mod dependencies.

I tryed version v2.9.10, v2.9.9 and v2.6.0 without luck.

Does this mod not work with 1.18.10?

**Comment by egocarib** [comment]
v2.9.10 would be my best guess as to which might work with 1.18.10.

Unfortunately the 1.18.* series of releases had a lot of breaking changes, and it's hard to support them all. I will only have time to support the latest 1.18 version (1.18.15), especially now that 1.19 is released.
