### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by GIGAAj1** [egocarib/Vintage-Story-Mods#5]
Hi i translated the mod in German(de) because i play in german and for me the Overlay was broken (but cinnebar bits and so are not working but i have them written down (in Menu order))

![image](https://user-images.githubusercontent.com/2996236/185751485-6b7db753-bb0a-49bd-b20f-fd2a12c822df.png)

{
"egocarib-mapmarkers:modname": "Auto Map Marker",
"egocarib-mapmarkers:config-keybind-name": "Auto Map Marker Konfiguration",
"egocarib-mapmarkers:config-keybind-custom1": "Benutzerdefinierte Markierung hinzufügen 1",
"egocarib-mapmarkers:config-keybind-custom2": "Benutzerdefinierte Markierung hinzufügen 2",
"egocarib-mapmarkers:config-keybind-custom3": "Benutzerdefinierte Markierung hinzufügen 3",
"egocarib-mapmarkers:config-keybind-delete-nearest": "Nächstgelegene Kartenmarkierung löschen",
"egocarib-mapmarkers:config-menu-title": "Auto Map Marker Einstellungen",
"egocarib-mapmarkers:config-menu-section-header1": "Automatische Kartenmarkierungen",
"egocarib-mapmarkers:icon": "Symbol",
"egocarib-mapmarkers:color": "Farbe",
"egocarib-mapmarkers:name": "Name",
"egocarib-mapmarkers:disabled": "Deaktiviert",
"egocarib-mapmarkers:not-saved-warning": "Auto Map Marker Einstellungen nicht gespeichert: Die Einstellungen enthielten ungültige Farben oder Namen.",
"egocarib-mapmarkers:organic-matter": "Organische Materie",
"egocarib-mapmarkers:surface-ore": "Oberflächenerz",
"egocarib-mapmarkers:traders": "Händler",
"egocarib-mapmarkers:custom": "Benutzerdefiniert",
"egocarib-mapmarkers:custom-marker-1": "Benutzerdefinierte Markierung 1",
"egocarib-mapmarkers:custom-marker-2": "Benutzerdefinierte Markierung 2",
"egocarib-mapmarkers:custom-marker-3": "Benutzerdefinierte Markierung 3",
"egocarib-mapmarkers:custom-gui-description": "Konfigurieren Sie Hotkeys für diese Markierungen im Spieleinstellungsmenü (Esc > Einstellungen > Steuerung).",
"egocarib-mapmarkers:copy-setting-to-all-traders": "Symbol und Farbe von \"{0}\" nach „Alle“ kopieren",
"egocarib-mapmarkers:anthracite-ore-bits": "Anthrazitsplitter",
"egocarib-mapmarkers:bituminouscoal-ore-bits": "Steinkohlesplitter",
"egocarib-mapmarkers:borax-ore-bits": "Boraxsplitter",
"egocarib-mapmarkers:lignite-ore-bits": "Braunkohlesplitter",
"egocarib-mapmarkers:cinnabar-ore-bits": "Zinnobersplitter",
"egocarib-mapmarkers:copper-ore-bits": "Kupfersplitter",
"egocarib-mapmarkers:gold-ore-bits": "Goldsplitter",
"egocarib-mapmarkers:lapislazuli-ore-bits": "Lapislazulisplitter",
"egocarib-mapmarkers:galena-ore-bits": "Bleisplitter",
"egocarib-mapmarkers:olivine-ore-bits": "Olivinsplitter",
"egocarib-mapmarkers:quartz-ore-bits": "Quarzsplitter",
"egocarib-mapmarkers:silver-ore-bits": "Silbersplitter",
"egocarib-mapmarkers:sulfur-ore-bits": "Schwefelsplitter",
"egocarib-mapmarkers:cassiterite-ore-bits": "Zinnsplitter",
"egocarib-mapmarkers:ui": "UI",
"egocarib-mapmarkers:show-chat-message": "Chatnachricht anzeigen, wenn eine neue Kartenmarkierung hinzugefügt wird",
"egocarib-mapmarkers:enable-custom-hotkeys": "Aktiviert Hotkeys, um anpassbare Kartenmarkierungen hinzuzufügen",
"egocarib-mapmarkers:enable-delete-hotkey": "Aktiviert den Hotkey, um die nächste Kartenmarkierung zu löschen",
"egocarib-mapmarkers:show-chat-message-on-delete": "Chatnachricht anzeigen, wenn die nächste Kartenmarkierung gelöscht wird",
"egocarib-mapmarkers:show-chat-message-hotkey-tooltip": "Nachdem Sie diese Option aktiviert haben, können Sie die Hotkeys in den Spieleinstellungen konfigurieren (Esc > Einstellungen > Steuerung).",
"egocarib-mapmarkers:disable-mod": "Deaktivieren Sie vorübergehend den Auto Map Markers mod",
"egocarib-mapmarkers:re-enable-mod": "Klicken Sie hier, um den Auto Map Markers mod zu aktivieren ",
"egocarib-mapmarkers:server-warning": "Auto Map Markers mod konnte keine Verbindung zum Server herstellen und funktioniert möglicherweise nicht wie erwartet. Wenn Sie sich auf einem Multiplayer-Server befinden, muss der Mod auf dem Server installiert werden, um zu funktionieren."
}

**Comment by egocarib** [comment]
Thank you!

I'll look into adding this translation soon for the next version I release.
